### ISSUE TITLE
wine: cannot find 

### ISSUE THREAD

**Issue by gearcapitan** [curtis992250/shecodject#1]
![kali_linux-2018-03-27-14-06-26](https://user-images.githubusercontent.com/13740942/37992115-10f96b1a-31c8-11e8-8144-daf2f22abaf6.png)

**Comment by TaroballzChen** [comment]
you need to install wine32 and reinstall python3.4 msi format file or you can pack the .py file to exe format in windows enviroment

**Comment by TaroballzChen** [comment]
I already solved this problem by docker, you can pack the python file in pytinstaller-windows/x86 container.  good luck!
