### ISSUE TITLE
docker配製

### ISSUE THREAD

**Issue by yuhaoze002** [curtis992250/shecodject#2]
問一下問題，運行之後出現docker配製的錯誤，如下：
Unable to find image 'cdrx/pyinstaller-windows:python3-32bit' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate has expired or is not yet valid.
See 'docker run --help'.
Traceback (most recent call last):
  File "shecodject.py", line 61, in <module>
    mod.do_action(ui.banner)
  File "/root/tools/shecodject/module/module.py", line 49, in do_action
    self.exec_action(action)
  File "/root/tools/shecodject/module/module.py", line 34, in exec_action
    self.run_action()
  File "/root/tools/shecodject/module/make_exe.py", line 83, in run_action
    self.docker_pack(self.values["outfile"])
  File "/root/tools/shecodject/module/make_exe.py", line 66, in docker_pack
    shutil.copy("./output/src/dist/windows/%s"%file,"./output/")
  File "/usr/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './output/src/dist/windows/05202074.exe'
小白想問一下docker如何配置，可否在readme裡面更新一下

**Comment by TaroballzChen** [comment]
你好 你似乎沒有正確pull pyinstaller的docker image

請在終端確認
```
~$ docker images
```

是否有此項目
```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
cdrx/pyinstaller-windows   python3-32bit       e07b098ba8b2        4 months ago        1.76GB
```

沒有的話 請手動pull
```
~$ docker pull cdrx/pyinstaller-windows:python3-32bit
```
- 可參考docker hub <https://hub.docker.com/r/cdrx/pyinstaller-windows>

**Comment by fsocietyjack** [comment]
awsome man you re so good!!!

**Comment by yuhaoze002** [comment]
非常感謝，解決了
中途docker pull遇到一個問題：
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate has expired or is not yet valid
查閱發現是本地系統時間錯誤導致報錯證書過期，解決方法（kali）:
apt-get install ntpdate
ntpdate cn.pool.ntp.org
docker pull cdrx/pyinstaller-windows:python3-32bit
