### ISSUE TITLE
无法在windows7/winserver2008中成功回连

### ISSUE THREAD

**Issue by SmileB0mb** [curtis992250/shecodject#3]
生成的reverse/winhttps payload 的raw ，经过shecodject.py封装成exe后无法在windows7/winserver2008中成功回连

**Comment by TaroballzChen** [comment]
你好，非常感謝反饋，請確定生成的證書是否過期，或是重新申請證書之後，再次重新使用msfvenom生成payload，另外不一定得使用winhttps的payload，只要是x86的windows payload都能使用，我這邊使用windows7跟winserver 2008都是能成功回連的。

**Comment by SmileB0mb** [comment]
好的，谢谢
